FROM docker.io/library/ubuntu:22.04 AS build
RUN bash <<EOF
set -euxo pipefail
apt-get update
apt-get -y install curl
curl -O https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/arm64/cuda-keyring_1.1-1_all.deb
dpkg -i cuda-keyring_1.1-1_all.deb
apt-get update
apt-get -y install \
  cuda-cupti-12-8 \
  cuda-nvrtc-12-8 \
  libcudnn9-cuda-12 \
  libcublas-12-8 \
  cuda-cudart-12-8 \
  libcufft-12-8 \
  libcusparse-12-8 \
  libcusparselt0 \
  libcusolver-12-8 \
  libcurand-12-8 \
  libcufile-12-8 \
  libnvtoolsext1 \
  libnvjitlink-12-8
EOF
# Reference: .ci/aarch64_linux/aarch64_wheel_ci_build.py
FROM scratch
COPY --from=build --chmod=0555 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libcupti.so.12 \
  /usr/lib/aarch64-linux-gnu/libcudnn.so.9 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libcublas.so.12 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libcublasLt.so.12 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libcudart.so.12 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libcufft.so.11 \
  /usr/local/cuda/lib64/libcusparse.so.12 \
  /usr/lib/aarch64-linux-gnu/libcusparseLt.so.0 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libcusolver.so.11 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libcurand.so.10 \
  /usr/lib/aarch64-linux-gnu/libnvToolsExt.so.1 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libnvJitLink.so.12 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libnvrtc.so.12 \
  /usr/lib/aarch64-linux-gnu/libcudnn_adv.so.9 \
  /usr/lib/aarch64-linux-gnu/libcudnn_cnn.so.9 \
  /usr/lib/aarch64-linux-gnu/libcudnn_graph.so.9 \
  /usr/lib/aarch64-linux-gnu/libcudnn_ops.so.9 \
  /usr/lib/aarch64-linux-gnu/libcudnn_engines_runtime_compiled.so.9 \
  /usr/lib/aarch64-linux-gnu/libcudnn_engines_precompiled.so.9 \
  /usr/lib/aarch64-linux-gnu/libcudnn_heuristic.so.9 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libnvrtc-builtins.so.12.8 \
  /usr/local/cuda-12.8/targets/aarch64-linux/lib/libcufile.so.0 \
  /lib
