FROM docker.io/rockylinux/rockylinux:9.4
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN <<EOF
set -e
dnf install -y python3.11
dnf clean all
EOF

RUN <<EOF
set -e
export UV_PYTHON=/usr/bin/python3.11
uv venv
uv pip install torch torchvision torchaudio pytorch-triton --index-url https://download.pytorch.org/whl/nightly/cu129
EOF
