name: ci
on:
  push:
jobs:
  docker:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: docker/login-action@v3
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
