name: ci
on:
  push:
jobs:
  docker:
    runs-on: ubuntu-24.04-arm
    container:
      image: registry.access.redhat.com/ubi9/ubi
      options: --privileged -v /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Access a subscription via activation key
        run: |
          subscription-manager register --org=${{ secrets.RHT_ORGID }} --activationkey=${{ secrets.RHT_ACT_KEY }}
      - name: Install docker
        run: |
          dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
          dnf install -y docker-ce-cli docker-buildx-plugin docker-compose-plugin
      - uses: docker/login-action@v3
        with:
          registry: registry.redhat.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
      - name: Clean up the subscription
        if: always()
        run: |
          subscription-manager unregister
